---
version: '3.8'

services:
  reg-frontend:
    image: reg-frontend
    build: ./reg-frontend
    ports:
      - 3000:3000
    environment:
      - reg-backend=reg-backend
    volumes:
      - ./reg-frontend/src/utils:/app/src/utils
      - ./reg-frontend/src/types:/app/src/types
      - ./reg-frontend/src/store:/app/src/store
      - ./reg-frontend/src/public:/app/src/public
      - ./reg-frontend/src/pages:/app/src/pages
      - ./reg-frontend/src/components:/app/src/components
      - ./reg-frontend/src/assets:/app/src/assets
     
    

  reg-backend:
    image: reg-backend
    build: ./reg-backend
    ports:
      - 8000:8000
    volumes:
      - ./reg-backend/src:/app/src
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=devdb
    #   - DB_USER=devuser
    #   - DB_PASS=password
    
    # depends_on:
    #   - db
    
#   pgadmin:
#     image: dpage/pgadmin4:latest
#     restart:  always
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=root@root.com
#       - PGADMIN_DEFAULT_PASSWORD=root
#     ports:
#       - "5050:80"

#   db:
#     container_name: postgresql_db
#     image: postgres:latest
#     volumes:
#       - dev-db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_USER=root
#       - POSTGRES_PASSWORD=root
#       - POSTGRES_DB=testdb
#     ports:
#       - "5432:5432"

  

# volumes:
#   dev-db-data:

    
