export default interface IPayment{
    [x: string]: any;
    paymentId: string,
    entity: string,
    amount: number,
    currency: string,
    status: string,
    order_id: string,
    invoice_id: string|null,
    international: boolean,
    method: string,
    amount_refunded: number,
    refund_status: string|null,
    captured: boolean,
    description: string,
    card_id: null,
    bank: string|null,
    wallet: null,
    vpa: null,
    email: string|null,
    contact: string|null,
    notes: [],
    fee: number,
    tax: number,
    error_code: null,
    error_description: null,
    error_source: null,
    error_step: null,
    error_reason: null,
    acquirer_data: { bank_transaction_id: string|null },
    created_at: Number
}